run:
	go run .

unit:
	go test ./... -cover
 
build_all:
	GOOS=windows GOARCH=386 go build -o bin/terun-386.exe ./...
	GOOS=windows GOARCH=amd64 go build -o bin/terun-amd64.exe ./...
	GOOS=darwin GOARCH=amd64 go build -o bin/terun-amd64-darwin ./...
	GOOS=linux GOARCH=amd64 go build -o bin/terun-amd64-linux ./...
	GOOS=linux GOARCH=386 go build -o bin/terun-386-linux ./...



